package com.example.jocke.kotlin.data.dal;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.jocke.kotlin.data.dal.Team;

import com.example.jocke.kotlin.data.dal.TeamDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teamDaoConfig;

    private final TeamDao teamDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teamDaoConfig = daoConfigMap.get(TeamDao.class).clone();
        teamDaoConfig.initIdentityScope(type);

        teamDao = new TeamDao(teamDaoConfig, this);

        registerDao(Team.class, teamDao);
    }
    
    public void clear() {
        teamDaoConfig.clearIdentityScope();
    }

    public TeamDao getTeamDao() {
        return teamDao;
    }

}
